
export const COUNTRIES = [
    // DATA START
    {alpha2: 'AD', alpha3: 'AND', numeric: 'N020', name: 'Andorra', official_name: 'the Principality of Andorra'},
    {alpha2: 'AE', alpha3: 'ARE', numeric: 'N784', name: 'United Arab Emirates (the)', official_name: 'the United Arab Emirates'},
    {alpha2: 'AF', alpha3: 'AFG', numeric: 'N004', name: 'Afghanistan', official_name: 'the Islamic Republic of Afghanistan'},
    {alpha2: 'AG', alpha3: 'ATG', numeric: 'N028', name: 'Antigua and Barbuda', official_name: ''},
    {alpha2: 'AI', alpha3: 'AIA', numeric: 'N660', name: 'Anguilla', official_name: ''},
    {alpha2: 'AL', alpha3: 'ALB', numeric: 'N008', name: 'Albania', official_name: 'the Republic of Albania'},
    {alpha2: 'AM', alpha3: 'ARM', numeric: 'N051', name: 'Armenia', official_name: 'the Republic of Armenia'},
    {alpha2: 'AO', alpha3: 'AGO', numeric: 'N024', name: 'Angola', official_name: 'the Republic of Angola'},
    {alpha2: 'AQ', alpha3: 'ATA', numeric: 'N010', name: 'Antarctica', official_name: ''},
    {alpha2: 'AR', alpha3: 'ARG', numeric: 'N032', name: 'Argentina', official_name: 'the Argentine Republic'},
    {alpha2: 'AS', alpha3: 'ASM', numeric: 'N016', name: 'American Samoa', official_name: ''},
    {alpha2: 'AT', alpha3: 'AUT', numeric: 'N040', name: 'Austria', official_name: 'the Republic of Austria'},
    {alpha2: 'AU', alpha3: 'AUS', numeric: 'N036', name: 'Australia', official_name: ''},
    {alpha2: 'AW', alpha3: 'ABW', numeric: 'N533', name: 'Aruba', official_name: ''},
    {alpha2: 'AX', alpha3: 'ALA', numeric: 'N248', name: 'Åland Islands', official_name: ''},
    {alpha2: 'AZ', alpha3: 'AZE', numeric: 'N031', name: 'Azerbaijan', official_name: 'the Republic of Azerbaijan'},
    {alpha2: 'BA', alpha3: 'BIH', numeric: 'N070', name: 'Bosnia and Herzegovina', official_name: ''},
    {alpha2: 'BB', alpha3: 'BRB', numeric: 'N052', name: 'Barbados', official_name: ''},
    {alpha2: 'BD', alpha3: 'BGD', numeric: 'N050', name: 'Bangladesh', official_name: 'the People\'s Republic of Bangladesh'},
    {alpha2: 'BE', alpha3: 'BEL', numeric: 'N056', name: 'Belgium', official_name: 'the Kingdom of Belgium'},
    {alpha2: 'BF', alpha3: 'BFA', numeric: 'N854', name: 'Burkina Faso', official_name: ''},
    {alpha2: 'BG', alpha3: 'BGR', numeric: 'N100', name: 'Bulgaria', official_name: 'the Republic of Bulgaria'},
    {alpha2: 'BH', alpha3: 'BHR', numeric: 'N048', name: 'Bahrain', official_name: 'the Kingdom of Bahrain'},
    {alpha2: 'BI', alpha3: 'BDI', numeric: 'N108', name: 'Burundi', official_name: 'the Republic of Burundi'},
    {alpha2: 'BJ', alpha3: 'BEN', numeric: 'N204', name: 'Benin', official_name: 'the Republic of Benin'},
    {alpha2: 'BL', alpha3: 'BLM', numeric: 'N652', name: 'Saint Barthélemy', official_name: ''},
    {alpha2: 'BM', alpha3: 'BMU', numeric: 'N060', name: 'Bermuda', official_name: ''},
    {alpha2: 'BN', alpha3: 'BRN', numeric: 'N096', name: 'Brunei Darussalam', official_name: ''},
    {alpha2: 'BO', alpha3: 'BOL', numeric: 'N068', name: 'Bolivia (Plurinational State of)', official_name: 'the Plurinational State of Bolivia'},
    {alpha2: 'BQ', alpha3: 'BES', numeric: 'N535', name: 'Bonaire, Sint Eustatius and Saba', official_name: ''},
    {alpha2: 'BR', alpha3: 'BRA', numeric: 'N076', name: 'Brazil', official_name: 'the Federative Republic of Brazil'},
    {alpha2: 'BS', alpha3: 'BHS', numeric: 'N044', name: 'Bahamas (the)', official_name: 'the Commonwealth of the Bahamas'},
    {alpha2: 'BT', alpha3: 'BTN', numeric: 'N064', name: 'Bhutan', official_name: 'the Kingdom of Bhutan'},
    {alpha2: 'BV', alpha3: 'BVT', numeric: 'N074', name: 'Bouvet Island', official_name: ''},
    {alpha2: 'BW', alpha3: 'BWA', numeric: 'N072', name: 'Botswana', official_name: 'the Republic of Botswana'},
    {alpha2: 'BY', alpha3: 'BLR', numeric: 'N112', name: 'Belarus', official_name: 'the Republic of Belarus'},
    {alpha2: 'BZ', alpha3: 'BLZ', numeric: 'N084', name: 'Belize', official_name: ''},
    {alpha2: 'CA', alpha3: 'CAN', numeric: 'N124', name: 'Canada', official_name: ''},
    {alpha2: 'CC', alpha3: 'CCK', numeric: 'N166', name: 'Cocos (Keeling) Islands (the)', official_name: ''},
    {alpha2: 'CD', alpha3: 'COD', numeric: 'N180', name: 'Congo (the Democratic Republic of the)', official_name: 'the Democratic Republic of the Congo'},
    {alpha2: 'CF', alpha3: 'CAF', numeric: 'N140', name: 'Central African Republic (the)', official_name: 'the Central African Republic'},
    {alpha2: 'CG', alpha3: 'COG', numeric: 'N178', name: 'Congo (the)', official_name: 'the Republic of the Congo'},
    {alpha2: 'CH', alpha3: 'CHE', numeric: 'N756', name: 'Switzerland', official_name: 'the Swiss Confederation'},
    {alpha2: 'CI', alpha3: 'CIV', numeric: 'N384', name: 'Côte d\'Ivoire', official_name: 'the Republic of Côte d\'Ivoire'},
    {alpha2: 'CK', alpha3: 'COK', numeric: 'N184', name: 'Cook Islands (the)', official_name: ''},
    {alpha2: 'CL', alpha3: 'CHL', numeric: 'N152', name: 'Chile', official_name: 'the Republic of Chile'},
    {alpha2: 'CM', alpha3: 'CMR', numeric: 'N120', name: 'Cameroon', official_name: 'the Republic of Cameroon'},
    {alpha2: 'CN', alpha3: 'CHN', numeric: 'N156', name: 'China', official_name: 'the People\'s Republic of China'},
    {alpha2: 'CO', alpha3: 'COL', numeric: 'N170', name: 'Colombia', official_name: 'the Republic of Colombia'},
    {alpha2: 'CR', alpha3: 'CRI', numeric: 'N188', name: 'Costa Rica', official_name: 'the Republic of Costa Rica'},
    {alpha2: 'CU', alpha3: 'CUB', numeric: 'N192', name: 'Cuba', official_name: 'the Republic of Cuba'},
    {alpha2: 'CV', alpha3: 'CPV', numeric: 'N132', name: 'Cabo Verde', official_name: 'the Republic of Cabo Verde'},
    {alpha2: 'CW', alpha3: 'CUW', numeric: 'N531', name: 'Curaçao', official_name: ''},
    {alpha2: 'CX', alpha3: 'CXR', numeric: 'N162', name: 'Christmas Island', official_name: ''},
    {alpha2: 'CY', alpha3: 'CYP', numeric: 'N196', name: 'Cyprus', official_name: 'the Republic of Cyprus'},
    {alpha2: 'CZ', alpha3: 'CZE', numeric: 'N203', name: 'Czechia', official_name: 'the Czech Republic'},
    {alpha2: 'DE', alpha3: 'DEU', numeric: 'N276', name: 'Germany', official_name: 'the Federal Republic of Germany'},
    {alpha2: 'DJ', alpha3: 'DJI', numeric: 'N262', name: 'Djibouti', official_name: 'the Republic of Djibouti'},
    {alpha2: 'DK', alpha3: 'DNK', numeric: 'N208', name: 'Denmark', official_name: 'the Kingdom of Denmark'},
    {alpha2: 'DM', alpha3: 'DMA', numeric: 'N212', name: 'Dominica', official_name: 'the Commonwealth of Dominica'},
    {alpha2: 'DO', alpha3: 'DOM', numeric: 'N214', name: 'Dominican Republic (the)', official_name: 'the Dominican Republic'},
    {alpha2: 'DZ', alpha3: 'DZA', numeric: 'N012', name: 'Algeria', official_name: 'the People\'s Democratic Republic of Algeria'},
    {alpha2: 'EC', alpha3: 'ECU', numeric: 'N218', name: 'Ecuador', official_name: 'the Republic of Ecuador'},
    {alpha2: 'EE', alpha3: 'EST', numeric: 'N233', name: 'Estonia', official_name: 'the Republic of Estonia'},
    {alpha2: 'EG', alpha3: 'EGY', numeric: 'N818', name: 'Egypt', official_name: 'the Arab Republic of Egypt'},
    {alpha2: 'EH', alpha3: 'ESH', numeric: 'N732', name: 'Western Sahara*', official_name: ''},
    {alpha2: 'ER', alpha3: 'ERI', numeric: 'N232', name: 'Eritrea', official_name: 'the State of Eritrea'},
    {alpha2: 'ES', alpha3: 'ESP', numeric: 'N724', name: 'Spain', official_name: 'the Kingdom of Spain'},
    {alpha2: 'ET', alpha3: 'ETH', numeric: 'N231', name: 'Ethiopia', official_name: 'the Federal Democratic Republic of Ethiopia'},
    {alpha2: 'FI', alpha3: 'FIN', numeric: 'N246', name: 'Finland', official_name: 'the Republic of Finland'},
    {alpha2: 'FJ', alpha3: 'FJI', numeric: 'N242', name: 'Fiji', official_name: 'the Republic of Fiji'},
    {alpha2: 'FK', alpha3: 'FLK', numeric: 'N238', name: 'Falkland Islands (the) [Malvinas]', official_name: ''},
    {alpha2: 'FM', alpha3: 'FSM', numeric: 'N583', name: 'Micronesia (Federated States of)', official_name: 'the Federated States of Micronesia'},
    {alpha2: 'FO', alpha3: 'FRO', numeric: 'N234', name: 'Faroe Islands (the)', official_name: ''},
    {alpha2: 'FR', alpha3: 'FRA', numeric: 'N250', name: 'France', official_name: 'the French Republic'},
    {alpha2: 'GA', alpha3: 'GAB', numeric: 'N266', name: 'Gabon', official_name: 'the Gabonese Republic'},
    {alpha2: 'GB', alpha3: 'GBR', numeric: 'N826', name: 'United Kingdom of Great Britain and Northern Ireland (the)', official_name: 'the United Kingdom of Great Britain and Northern Ireland'},
    {alpha2: 'GD', alpha3: 'GRD', numeric: 'N308', name: 'Grenada', official_name: ''},
    {alpha2: 'GE', alpha3: 'GEO', numeric: 'N268', name: 'Georgia', official_name: ''},
    {alpha2: 'GF', alpha3: 'GUF', numeric: 'N254', name: 'French Guiana', official_name: ''},
    {alpha2: 'GG', alpha3: 'GGY', numeric: 'N831', name: 'Guernsey', official_name: ''},
    {alpha2: 'GH', alpha3: 'GHA', numeric: 'N288', name: 'Ghana', official_name: 'the Republic of Ghana'},
    {alpha2: 'GI', alpha3: 'GIB', numeric: 'N292', name: 'Gibraltar', official_name: ''},
    {alpha2: 'GL', alpha3: 'GRL', numeric: 'N304', name: 'Greenland', official_name: ''},
    {alpha2: 'GM', alpha3: 'GMB', numeric: 'N270', name: 'Gambia (the)', official_name: 'the Republic of the Gambia'},
    {alpha2: 'GN', alpha3: 'GIN', numeric: 'N324', name: 'Guinea', official_name: 'the Republic of Guinea'},
    {alpha2: 'GP', alpha3: 'GLP', numeric: 'N312', name: 'Guadeloupe', official_name: ''},
    {alpha2: 'GQ', alpha3: 'GNQ', numeric: 'N226', name: 'Equatorial Guinea', official_name: 'the Republic of Equatorial Guinea'},
    {alpha2: 'GR', alpha3: 'GRC', numeric: 'N300', name: 'Greece', official_name: 'the Hellenic Republic'},
    {alpha2: 'GS', alpha3: 'SGS', numeric: 'N239', name: 'South Georgia and the South Sandwich Islands', official_name: ''},
    {alpha2: 'GT', alpha3: 'GTM', numeric: 'N320', name: 'Guatemala', official_name: 'the Republic of Guatemala'},
    {alpha2: 'GU', alpha3: 'GUM', numeric: 'N316', name: 'Guam', official_name: ''},
    {alpha2: 'GW', alpha3: 'GNB', numeric: 'N624', name: 'Guinea-Bissau', official_name: 'the Republic of Guinea-Bissau'},
    {alpha2: 'GY', alpha3: 'GUY', numeric: 'N328', name: 'Guyana', official_name: 'the Co-operative Republic of Guyana'},
    {alpha2: 'HK', alpha3: 'HKG', numeric: 'N344', name: 'Hong Kong', official_name: 'the Hong Kong Special Administrative Region of China'},
    {alpha2: 'HM', alpha3: 'HMD', numeric: 'N334', name: 'Heard Island and McDonald Islands', official_name: ''},
    {alpha2: 'HN', alpha3: 'HND', numeric: 'N340', name: 'Honduras', official_name: 'the Republic of Honduras'},
    {alpha2: 'HR', alpha3: 'HRV', numeric: 'N191', name: 'Croatia', official_name: 'the Republic of Croatia'},
    {alpha2: 'HT', alpha3: 'HTI', numeric: 'N332', name: 'Haiti', official_name: 'the Republic of Haiti'},
    {alpha2: 'HU', alpha3: 'HUN', numeric: 'N348', name: 'Hungary', official_name: ''},
    {alpha2: 'ID', alpha3: 'IDN', numeric: 'N360', name: 'Indonesia', official_name: 'the Republic of Indonesia'},
    {alpha2: 'IE', alpha3: 'IRL', numeric: 'N372', name: 'Ireland', official_name: ''},
    {alpha2: 'IL', alpha3: 'ISR', numeric: 'N376', name: 'Israel', official_name: 'the State of Israel'},
    {alpha2: 'IM', alpha3: 'IMN', numeric: 'N833', name: 'Isle of Man', official_name: ''},
    {alpha2: 'IN', alpha3: 'IND', numeric: 'N356', name: 'India', official_name: 'the Republic of India'},
    {alpha2: 'IO', alpha3: 'IOT', numeric: 'N086', name: 'British Indian Ocean Territory (the)', official_name: ''},
    {alpha2: 'IQ', alpha3: 'IRQ', numeric: 'N368', name: 'Iraq', official_name: 'the Republic of Iraq'},
    {alpha2: 'IR', alpha3: 'IRN', numeric: 'N364', name: 'Iran (Islamic Republic of)', official_name: 'the Islamic Republic of Iran'},
    {alpha2: 'IS', alpha3: 'ISL', numeric: 'N352', name: 'Iceland', official_name: 'the Republic of Iceland'},
    {alpha2: 'IT', alpha3: 'ITA', numeric: 'N380', name: 'Italy', official_name: 'the Republic of Italy'},
    {alpha2: 'JE', alpha3: 'JEY', numeric: 'N832', name: 'Jersey', official_name: ''},
    {alpha2: 'JM', alpha3: 'JAM', numeric: 'N388', name: 'Jamaica', official_name: ''},
    {alpha2: 'JO', alpha3: 'JOR', numeric: 'N400', name: 'Jordan', official_name: 'the Hashemite Kingdom of Jordan'},
    {alpha2: 'JP', alpha3: 'JPN', numeric: 'N392', name: 'Japan', official_name: ''},
    {alpha2: 'KE', alpha3: 'KEN', numeric: 'N404', name: 'Kenya', official_name: 'the Republic of Kenya'},
    {alpha2: 'KG', alpha3: 'KGZ', numeric: 'N417', name: 'Kyrgyzstan', official_name: 'the Kyrgyz Republic'},
    {alpha2: 'KH', alpha3: 'KHM', numeric: 'N116', name: 'Cambodia', official_name: 'the Kingdom of Cambodia'},
    {alpha2: 'KI', alpha3: 'KIR', numeric: 'N296', name: 'Kiribati', official_name: 'the Republic of Kiribati'},
    {alpha2: 'KM', alpha3: 'COM', numeric: 'N174', name: 'Comoros (the)', official_name: 'the Union of the Comoros'},
    {alpha2: 'KN', alpha3: 'KNA', numeric: 'N659', name: 'Saint Kitts and Nevis', official_name: ''},
    {alpha2: 'KP', alpha3: 'PRK', numeric: 'N408', name: 'Korea (the Democratic People\'s Republic of)', official_name: 'the Democratic People\'s Republic of Korea'},
    {alpha2: 'KR', alpha3: 'KOR', numeric: 'N410', name: 'Korea (the Republic of)', official_name: 'the Republic of Korea'},
    {alpha2: 'KW', alpha3: 'KWT', numeric: 'N414', name: 'Kuwait', official_name: 'the State of Kuwait'},
    {alpha2: 'KY', alpha3: 'CYM', numeric: 'N136', name: 'Cayman Islands (the)', official_name: ''},
    {alpha2: 'KZ', alpha3: 'KAZ', numeric: 'N398', name: 'Kazakhstan', official_name: 'the Republic of Kazakhstan'},
    {alpha2: 'LA', alpha3: 'LAO', numeric: 'N418', name: 'Lao People\'s Democratic Republic (the)', official_name: 'the Lao People\'s Democratic Republic'},
    {alpha2: 'LB', alpha3: 'LBN', numeric: 'N422', name: 'Lebanon', official_name: 'the Lebanese Republic'},
    {alpha2: 'LC', alpha3: 'LCA', numeric: 'N662', name: 'Saint Lucia', official_name: ''},
    {alpha2: 'LI', alpha3: 'LIE', numeric: 'N438', name: 'Liechtenstein', official_name: 'the Principality of Liechtenstein'},
    {alpha2: 'LK', alpha3: 'LKA', numeric: 'N144', name: 'Sri Lanka', official_name: 'the Democratic Socialist Republic of Sri Lanka'},
    {alpha2: 'LR', alpha3: 'LBR', numeric: 'N430', name: 'Liberia', official_name: 'the Republic of Liberia'},
    {alpha2: 'LS', alpha3: 'LSO', numeric: 'N426', name: 'Lesotho', official_name: 'the Kingdom of Lesotho'},
    {alpha2: 'LT', alpha3: 'LTU', numeric: 'N440', name: 'Lithuania', official_name: 'the Republic of Lithuania'},
    {alpha2: 'LU', alpha3: 'LUX', numeric: 'N442', name: 'Luxembourg', official_name: 'the Grand Duchy of Luxembourg'},
    {alpha2: 'LV', alpha3: 'LVA', numeric: 'N428', name: 'Latvia', official_name: 'the Republic of Latvia'},
    {alpha2: 'LY', alpha3: 'LBY', numeric: 'N434', name: 'Libya', official_name: 'the State of Libya'},
    {alpha2: 'MA', alpha3: 'MAR', numeric: 'N504', name: 'Morocco', official_name: 'the Kingdom of Morocco'},
    {alpha2: 'MC', alpha3: 'MCO', numeric: 'N492', name: 'Monaco', official_name: 'the Principality of Monaco'},
    {alpha2: 'MD', alpha3: 'MDA', numeric: 'N498', name: 'Moldova (the Republic of)', official_name: 'the Republic of Moldova'},
    {alpha2: 'ME', alpha3: 'MNE', numeric: 'N499', name: 'Montenegro', official_name: ''},
    {alpha2: 'MF', alpha3: 'MAF', numeric: 'N663', name: 'Saint Martin (French part)', official_name: ''},
    {alpha2: 'MG', alpha3: 'MDG', numeric: 'N450', name: 'Madagascar', official_name: 'the Republic of Madagascar'},
    {alpha2: 'MH', alpha3: 'MHL', numeric: 'N584', name: 'Marshall Islands (the)', official_name: 'the Republic of the Marshall Islands'},
    {alpha2: 'MK', alpha3: 'MKD', numeric: 'N807', name: 'North Macedonia', official_name: 'the Republic of North Macedonia'},
    {alpha2: 'ML', alpha3: 'MLI', numeric: 'N466', name: 'Mali', official_name: 'the Republic of Mali'},
    {alpha2: 'MM', alpha3: 'MMR', numeric: 'N104', name: 'Myanmar', official_name: 'the Republic of the Union of Myanmar'},
    {alpha2: 'MN', alpha3: 'MNG', numeric: 'N496', name: 'Mongolia', official_name: ''},
    {alpha2: 'MO', alpha3: 'MAC', numeric: 'N446', name: 'Macao', official_name: 'Macao Special Administrative Region of China'},
    {alpha2: 'MP', alpha3: 'MNP', numeric: 'N580', name: 'Northern Mariana Islands (the)', official_name: 'the Commonwealth of the Northern Mariana Islands'},
    {alpha2: 'MQ', alpha3: 'MTQ', numeric: 'N474', name: 'Martinique', official_name: ''},
    {alpha2: 'MR', alpha3: 'MRT', numeric: 'N478', name: 'Mauritania', official_name: 'the Islamic Republic of Mauritania'},
    {alpha2: 'MS', alpha3: 'MSR', numeric: 'N500', name: 'Montserrat', official_name: ''},
    {alpha2: 'MT', alpha3: 'MLT', numeric: 'N470', name: 'Malta', official_name: 'the Republic of Malta'},
    {alpha2: 'MU', alpha3: 'MUS', numeric: 'N480', name: 'Mauritius', official_name: 'the Republic of Mauritius'},
    {alpha2: 'MV', alpha3: 'MDV', numeric: 'N462', name: 'Maldives', official_name: 'the Republic of Maldives'},
    {alpha2: 'MW', alpha3: 'MWI', numeric: 'N454', name: 'Malawi', official_name: 'the Republic of Malawi'},
    {alpha2: 'MX', alpha3: 'MEX', numeric: 'N484', name: 'Mexico', official_name: 'the United Mexican States'},
    {alpha2: 'MY', alpha3: 'MYS', numeric: 'N458', name: 'Malaysia', official_name: ''},
    {alpha2: 'MZ', alpha3: 'MOZ', numeric: 'N508', name: 'Mozambique', official_name: 'the Republic of Mozambique'},
    {alpha2: 'NA', alpha3: 'NAM', numeric: 'N516', name: 'Namibia', official_name: 'the Republic of Namibia'},
    {alpha2: 'NC', alpha3: 'NCL', numeric: 'N540', name: 'New Caledonia', official_name: ''},
    {alpha2: 'NE', alpha3: 'NER', numeric: 'N562', name: 'Niger (the)', official_name: 'the Republic of the Niger'},
    {alpha2: 'NF', alpha3: 'NFK', numeric: 'N574', name: 'Norfolk Island', official_name: ''},
    {alpha2: 'NG', alpha3: 'NGA', numeric: 'N566', name: 'Nigeria', official_name: 'the Federal Republic of Nigeria'},
    {alpha2: 'NI', alpha3: 'NIC', numeric: 'N558', name: 'Nicaragua', official_name: 'the Republic of Nicaragua'},
    {alpha2: 'NL', alpha3: 'NLD', numeric: 'N528', name: 'Netherlands (the)', official_name: 'the Kingdom of the Netherlands'},
    {alpha2: 'NO', alpha3: 'NOR', numeric: 'N578', name: 'Norway', official_name: 'the Kingdom of Norway'},
    {alpha2: 'NP', alpha3: 'NPL', numeric: 'N524', name: 'Nepal', official_name: ''},
    {alpha2: 'NR', alpha3: 'NRU', numeric: 'N520', name: 'Nauru', official_name: 'the Republic of Nauru'},
    {alpha2: 'NU', alpha3: 'NIU', numeric: 'N570', name: 'Niue', official_name: ''},
    {alpha2: 'NZ', alpha3: 'NZL', numeric: 'N554', name: 'New Zealand', official_name: ''},
    {alpha2: 'OM', alpha3: 'OMN', numeric: 'N512', name: 'Oman', official_name: 'the Sultanate of Oman'},
    {alpha2: 'PA', alpha3: 'PAN', numeric: 'N591', name: 'Panama', official_name: 'the Republic of Panama'},
    {alpha2: 'PE', alpha3: 'PER', numeric: 'N604', name: 'Peru', official_name: 'the Republic of Peru'},
    {alpha2: 'PF', alpha3: 'PYF', numeric: 'N258', name: 'French Polynesia', official_name: ''},
    {alpha2: 'PG', alpha3: 'PNG', numeric: 'N598', name: 'Papua New Guinea', official_name: 'the Independent State of Papua New Guinea'},
    {alpha2: 'PH', alpha3: 'PHL', numeric: 'N608', name: 'Philippines (the)', official_name: 'the Republic of the Philippines'},
    {alpha2: 'PK', alpha3: 'PAK', numeric: 'N586', name: 'Pakistan', official_name: 'the Islamic Republic of Pakistan'},
    {alpha2: 'PL', alpha3: 'POL', numeric: 'N616', name: 'Poland', official_name: 'the Republic of Poland'},
    {alpha2: 'PM', alpha3: 'SPM', numeric: 'N666', name: 'Saint Pierre and Miquelon', official_name: ''},
    {alpha2: 'PN', alpha3: 'PCN', numeric: 'N612', name: 'Pitcairn', official_name: ''},
    {alpha2: 'PR', alpha3: 'PRI', numeric: 'N630', name: 'Puerto Rico', official_name: ''},
    {alpha2: 'PS', alpha3: 'PSE', numeric: 'N275', name: 'Palestine, State of', official_name: 'the State of Palestine'},
    {alpha2: 'PT', alpha3: 'PRT', numeric: 'N620', name: 'Portugal', official_name: 'the Portuguese Republic'},
    {alpha2: 'PW', alpha3: 'PLW', numeric: 'N585', name: 'Palau', official_name: 'the Republic of Palau'},
    {alpha2: 'PY', alpha3: 'PRY', numeric: 'N600', name: 'Paraguay', official_name: 'the Republic of Paraguay'},
    {alpha2: 'QA', alpha3: 'QAT', numeric: 'N634', name: 'Qatar', official_name: 'the State of Qatar'},
    {alpha2: 'RE', alpha3: 'REU', numeric: 'N638', name: 'Réunion', official_name: ''},
    {alpha2: 'RO', alpha3: 'ROU', numeric: 'N642', name: 'Romania', official_name: ''},
    {alpha2: 'RS', alpha3: 'SRB', numeric: 'N688', name: 'Serbia', official_name: 'the Republic of Serbia'},
    {alpha2: 'RU', alpha3: 'RUS', numeric: 'N643', name: 'Russian Federation (the)', official_name: 'the Russian Federation'},
    {alpha2: 'RW', alpha3: 'RWA', numeric: 'N646', name: 'Rwanda', official_name: 'the Republic of Rwanda'},
    {alpha2: 'SA', alpha3: 'SAU', numeric: 'N682', name: 'Saudi Arabia', official_name: 'the Kingdom of Saudi Arabia'},
    {alpha2: 'SB', alpha3: 'SLB', numeric: 'N090', name: 'Solomon Islands', official_name: ''},
    {alpha2: 'SC', alpha3: 'SYC', numeric: 'N690', name: 'Seychelles', official_name: 'the Republic of Seychelles'},
    {alpha2: 'SD', alpha3: 'SDN', numeric: 'N729', name: 'Sudan (the)', official_name: 'the Republic of the Sudan'},
    {alpha2: 'SE', alpha3: 'SWE', numeric: 'N752', name: 'Sweden', official_name: 'the Kingdom of Sweden'},
    {alpha2: 'SG', alpha3: 'SGP', numeric: 'N702', name: 'Singapore', official_name: 'the Republic of Singapore'},
    {alpha2: 'SH', alpha3: 'SHN', numeric: 'N654', name: 'Saint Helena, Ascension and Tristan da Cunha', official_name: ''},
    {alpha2: 'SI', alpha3: 'SVN', numeric: 'N705', name: 'Slovenia', official_name: 'the Republic of Slovenia'},
    {alpha2: 'SJ', alpha3: 'SJM', numeric: 'N744', name: 'Svalbard and Jan Mayen', official_name: ''},
    {alpha2: 'SK', alpha3: 'SVK', numeric: 'N703', name: 'Slovakia', official_name: 'the Slovak Republic'},
    {alpha2: 'SL', alpha3: 'SLE', numeric: 'N694', name: 'Sierra Leone', official_name: 'the Republic of Sierra Leone'},
    {alpha2: 'SM', alpha3: 'SMR', numeric: 'N674', name: 'San Marino', official_name: 'the Republic of San Marino'},
    {alpha2: 'SN', alpha3: 'SEN', numeric: 'N686', name: 'Senegal', official_name: 'the Republic of Senegal'},
    {alpha2: 'SO', alpha3: 'SOM', numeric: 'N706', name: 'Somalia', official_name: 'the Federal Republic of Somalia'},
    {alpha2: 'SR', alpha3: 'SUR', numeric: 'N740', name: 'Suriname', official_name: 'the Republic of Suriname'},
    {alpha2: 'SS', alpha3: 'SSD', numeric: 'N728', name: 'South Sudan', official_name: 'the Republic of South Sudan'},
    {alpha2: 'ST', alpha3: 'STP', numeric: 'N678', name: 'Sao Tome and Principe', official_name: 'the Democratic Republic of Sao Tome and Principe'},
    {alpha2: 'SV', alpha3: 'SLV', numeric: 'N222', name: 'El Salvador', official_name: 'the Republic of El Salvador'},
    {alpha2: 'SX', alpha3: 'SXM', numeric: 'N534', name: 'Sint Maarten (Dutch part)', official_name: ''},
    {alpha2: 'SY', alpha3: 'SYR', numeric: 'N760', name: 'Syrian Arab Republic (the)', official_name: 'the Syrian Arab Republic'},
    {alpha2: 'SZ', alpha3: 'SWZ', numeric: 'N748', name: 'Eswatini', official_name: 'the Kingdom of Eswatini'},
    {alpha2: 'TC', alpha3: 'TCA', numeric: 'N796', name: 'Turks and Caicos Islands (the)', official_name: ''},
    {alpha2: 'TD', alpha3: 'TCD', numeric: 'N148', name: 'Chad', official_name: 'the Republic of Chad'},
    {alpha2: 'TF', alpha3: 'ATF', numeric: 'N260', name: 'French Southern Territories (the)', official_name: ''},
    {alpha2: 'TG', alpha3: 'TGO', numeric: 'N768', name: 'Togo', official_name: 'the Togolese Republic'},
    {alpha2: 'TH', alpha3: 'THA', numeric: 'N764', name: 'Thailand', official_name: 'the Kingdom of Thailand'},
    {alpha2: 'TJ', alpha3: 'TJK', numeric: 'N762', name: 'Tajikistan', official_name: 'the Republic of Tajikistan'},
    {alpha2: 'TK', alpha3: 'TKL', numeric: 'N772', name: 'Tokelau', official_name: ''},
    {alpha2: 'TL', alpha3: 'TLS', numeric: 'N626', name: 'Timor-Leste', official_name: 'the Democratic Republic of Timor-Leste'},
    {alpha2: 'TM', alpha3: 'TKM', numeric: 'N795', name: 'Turkmenistan', official_name: ''},
    {alpha2: 'TN', alpha3: 'TUN', numeric: 'N788', name: 'Tunisia', official_name: 'the Republic of Tunisia'},
    {alpha2: 'TO', alpha3: 'TON', numeric: 'N776', name: 'Tonga', official_name: 'the Kingdom of Tonga'},
    {alpha2: 'TR', alpha3: 'TUR', numeric: 'N792', name: 'Turkey', official_name: 'the Republic of Turkey'},
    {alpha2: 'TT', alpha3: 'TTO', numeric: 'N780', name: 'Trinidad and Tobago', official_name: 'the Republic of Trinidad and Tobago'},
    {alpha2: 'TV', alpha3: 'TUV', numeric: 'N798', name: 'Tuvalu', official_name: ''},
    {alpha2: 'TW', alpha3: 'TWN', numeric: 'N158', name: 'Taiwan (Province of China)', official_name: ''},
    {alpha2: 'TZ', alpha3: 'TZA', numeric: 'N834', name: 'Tanzania, the United Republic of', official_name: 'the United Republic of Tanzania'},
    {alpha2: 'UA', alpha3: 'UKR', numeric: 'N804', name: 'Ukraine', official_name: ''},
    {alpha2: 'UG', alpha3: 'UGA', numeric: 'N800', name: 'Uganda', official_name: 'the Republic of Uganda'},
    {alpha2: 'UM', alpha3: 'UMI', numeric: 'N581', name: 'United States Minor Outlying Islands (the)', official_name: ''},
    {alpha2: 'US', alpha3: 'USA', numeric: 'N840', name: 'United States of America (the)', official_name: 'the United States of America'},
    {alpha2: 'UY', alpha3: 'URY', numeric: 'N858', name: 'Uruguay', official_name: 'the Eastern Republic of Uruguay'},
    {alpha2: 'UZ', alpha3: 'UZB', numeric: 'N860', name: 'Uzbekistan', official_name: 'the Republic of Uzbekistan'},
    {alpha2: 'VA', alpha3: 'VAT', numeric: 'N336', name: 'Holy See (the)', official_name: ''},
    {alpha2: 'VC', alpha3: 'VCT', numeric: 'N670', name: 'Saint Vincent and the Grenadines', official_name: ''},
    {alpha2: 'VE', alpha3: 'VEN', numeric: 'N862', name: 'Venezuela (Bolivarian Republic of)', official_name: 'the Bolivarian Republic of Venezuela'},
    {alpha2: 'VG', alpha3: 'VGB', numeric: 'N092', name: 'Virgin Islands (British)', official_name: 'British Virgin Islands (the)'},
    {alpha2: 'VI', alpha3: 'VIR', numeric: 'N850', name: 'Virgin Islands (U.S.)', official_name: 'the Virgin Islands of the United States'},
    {alpha2: 'VN', alpha3: 'VNM', numeric: 'N704', name: 'Viet Nam', official_name: 'the Socialist Republic of Viet Nam'},
    {alpha2: 'VU', alpha3: 'VUT', numeric: 'N548', name: 'Vanuatu', official_name: 'the Republic of Vanuatu'},
    {alpha2: 'WF', alpha3: 'WLF', numeric: 'N876', name: 'Wallis and Futuna', official_name: 'Wallis and Futuna Islands'},
    {alpha2: 'WS', alpha3: 'WSM', numeric: 'N882', name: 'Samoa', official_name: 'the Independent State of Samoa'},
    {alpha2: 'YE', alpha3: 'YEM', numeric: 'N887', name: 'Yemen', official_name: 'the Republic of Yemen'},
    {alpha2: 'YT', alpha3: 'MYT', numeric: 'N175', name: 'Mayotte', official_name: ''},
    {alpha2: 'ZA', alpha3: 'ZAF', numeric: 'N710', name: 'South Africa', official_name: 'the Republic of South Africa'},
    {alpha2: 'ZM', alpha3: 'ZMB', numeric: 'N894', name: 'Zambia', official_name: 'the Republic of Zambia'},
    {alpha2: 'ZW', alpha3: 'ZWE', numeric: 'N716', name: 'Zimbabwe', official_name: 'the Republic of Zimbabwe'},
    // DATA END
];
